create table public.intake_moderation_events (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('citizen_report','municipal_request','parking_location')),
  entity_id uuid not null,
  public_reference text,
  action text not null check (char_length(action) between 2 and 80),
  previous_status text,
  new_status text,
  notes text check (notes is null or char_length(notes) <= 2000),
  actor_label text not null default 'inclume_team' check (char_length(actor_label) between 2 and 120),
  created_at timestamptz not null default now()
);

create index intake_moderation_events_entity_idx
  on public.intake_moderation_events (entity_type, entity_id, created_at desc);
create index intake_moderation_events_reference_idx
  on public.intake_moderation_events (public_reference, created_at desc);

alter table public.intake_moderation_events enable row level security;
revoke all on table public.intake_moderation_events from anon, authenticated;

create or replace function public.moderate_citizen_report(
  p_public_reference text,
  p_new_status text,
  p_notes text default null,
  p_actor_label text default 'inclume_team'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  report public.citizen_reports%rowtype;
  clean_reference text := upper(trim(p_public_reference));
  clean_actor text := coalesce(nullif(trim(p_actor_label), ''), 'inclume_team');
begin
  if p_new_status not in ('pending','triaged','needs_clarification','rejected','archived') then
    raise exception 'invalid citizen moderation status';
  end if;

  select * into report
  from public.citizen_reports
  where public_reference = clean_reference
  for update;

  if not found then
    raise exception 'citizen report not found';
  end if;

  update public.citizen_reports
  set status = p_new_status,
      reviewed_at = case when p_new_status = 'pending' then null else now() end,
      moderator_notes = p_notes
  where id = report.id;

  insert into public.intake_moderation_events (
    entity_type,
    entity_id,
    public_reference,
    action,
    previous_status,
    new_status,
    notes,
    actor_label
  ) values (
    'citizen_report',
    report.id,
    report.public_reference,
    'status_changed',
    report.status,
    p_new_status,
    p_notes,
    clean_actor
  );

  return report.id;
end;
$$;

create or replace function public.moderate_municipal_request(
  p_public_reference text,
  p_new_status text,
  p_notes text default null,
  p_actor_label text default 'inclume_team'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.municipal_pilot_requests%rowtype;
  clean_reference text := upper(trim(p_public_reference));
  clean_actor text := coalesce(nullif(trim(p_actor_label), ''), 'inclume_team');
begin
  if p_new_status not in ('new','contacted','meeting_scheduled','pilot_scoping','closed','archived') then
    raise exception 'invalid municipal request status';
  end if;

  select * into request_row
  from public.municipal_pilot_requests
  where public_reference = clean_reference
  for update;

  if not found then
    raise exception 'municipal request not found';
  end if;

  update public.municipal_pilot_requests
  set status = p_new_status,
      internal_notes = p_notes
  where id = request_row.id;

  insert into public.intake_moderation_events (
    entity_type,
    entity_id,
    public_reference,
    action,
    previous_status,
    new_status,
    notes,
    actor_label
  ) values (
    'municipal_request',
    request_row.id,
    request_row.public_reference,
    'status_changed',
    request_row.status,
    p_new_status,
    p_notes,
    clean_actor
  );

  return request_row.id;
end;
$$;

drop function if exists public.promote_citizen_report_to_parking(text,text,text,text,text);

create or replace function public.promote_citizen_report_to_parking(
  p_public_reference text,
  p_transfer_side text default 'unknown',
  p_step_free text default 'unknown',
  p_confidence_label text default 'community_reviewed',
  p_moderator_notes text default null,
  p_actor_label text default 'inclume_team'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  report public.citizen_reports%rowtype;
  parking_id uuid;
  clean_actor text := coalesce(nullif(trim(p_actor_label), ''), 'inclume_team');
begin
  if p_transfer_side not in ('unknown','right','left','both') then
    raise exception 'invalid transfer side';
  end if;
  if p_step_free not in ('unknown','yes','no') then
    raise exception 'invalid step free value';
  end if;
  if p_confidence_label not in ('community_reviewed','institutional','field_audit') then
    raise exception 'invalid confidence label';
  end if;

  select * into report
  from public.citizen_reports
  where public_reference = upper(trim(p_public_reference))
  for update;

  if not found then
    raise exception 'report not found';
  end if;
  if report.latitude is null or report.longitude is null then
    raise exception 'report requires coordinates before publication';
  end if;

  insert into public.parking_locations (
    name,
    location_reference,
    commune,
    latitude,
    longitude,
    transfer_side,
    step_free,
    notes,
    confidence_label,
    moderation_status,
    is_published,
    source_report_id
  ) values (
    report.place_name,
    report.exact_reference,
    report.commune,
    report.latitude,
    report.longitude,
    p_transfer_side,
    p_step_free,
    report.observation,
    p_confidence_label,
    'approved',
    true,
    report.id
  )
  on conflict (source_report_id)
  do update set
    name = excluded.name,
    location_reference = excluded.location_reference,
    commune = excluded.commune,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    transfer_side = excluded.transfer_side,
    step_free = excluded.step_free,
    notes = excluded.notes,
    confidence_label = excluded.confidence_label,
    moderation_status = 'approved',
    is_published = true,
    updated_at = now()
  returning id into parking_id;

  update public.citizen_reports
  set status = 'accepted',
      reviewed_at = now(),
      moderator_notes = p_moderator_notes
  where id = report.id;

  insert into public.intake_moderation_events (
    entity_type,
    entity_id,
    public_reference,
    action,
    previous_status,
    new_status,
    notes,
    actor_label
  ) values (
    'citizen_report',
    report.id,
    report.public_reference,
    'published_to_catalog',
    report.status,
    'accepted',
    p_moderator_notes,
    clean_actor
  );

  insert into public.intake_moderation_events (
    entity_type,
    entity_id,
    public_reference,
    action,
    previous_status,
    new_status,
    notes,
    actor_label
  ) values (
    'parking_location',
    parking_id,
    report.public_reference,
    'catalog_record_approved',
    null,
    'approved',
    p_moderator_notes,
    clean_actor
  );

  return parking_id;
end;
$$;

revoke all on function public.moderate_citizen_report(text,text,text,text) from public, anon, authenticated;
revoke all on function public.moderate_municipal_request(text,text,text,text) from public, anon, authenticated;
revoke all on function public.promote_citizen_report_to_parking(text,text,text,text,text,text) from public, anon, authenticated;

grant execute on function public.moderate_citizen_report(text,text,text,text) to service_role;
grant execute on function public.moderate_municipal_request(text,text,text,text) to service_role;
grant execute on function public.promote_citizen_report_to_parking(text,text,text,text,text,text) to service_role;

create view public.citizen_moderation_queue
with (security_invoker = true)
as
select
  id,
  public_reference,
  report_type,
  commune,
  place_name,
  exact_reference,
  latitude,
  longitude,
  observation,
  contact_email,
  status,
  created_at,
  updated_at,
  reviewed_at,
  moderator_notes
from public.citizen_reports
where status in ('pending','triaged','needs_clarification')
order by created_at asc;

create view public.municipal_moderation_queue
with (security_invoker = true)
as
select
  id,
  public_reference,
  institution,
  territory,
  contact_name,
  contact_role,
  institutional_email,
  phone,
  objective,
  problem_description,
  status,
  created_at,
  updated_at,
  internal_notes
from public.municipal_pilot_requests
where status not in ('closed','archived')
order by created_at asc;

revoke all on public.citizen_moderation_queue from anon, authenticated;
revoke all on public.municipal_moderation_queue from anon, authenticated;

comment on table public.intake_moderation_events is 'Historial inmutable de decisiones editoriales sobre reportes, solicitudes y catálogo.';
comment on function public.moderate_citizen_report(text,text,text,text) is 'Cambia el estado de un reporte ciudadano y registra el evento.';
comment on function public.moderate_municipal_request(text,text,text,text) is 'Cambia el estado de una solicitud municipal y registra el evento.';
